CREATE TABLE IF NOT EXISTS security.Users (
  Id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
  FullName VARCHAR(50) NOT NULL,
  Age INTEGER NOT NULL,
  Document VARCHAR(100) NOT NULL,
  DateCreated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  DateUpdated TIMESTAMP WITH TIME ZONE
);